=== tangxin1998/Si4/SI4/Web/xml/src/note.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT information (Student+)>
        <!ELEMENT Student (name,course,grade)>
        <!ATTLIST Student id1 CDATA #IMPLIED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT course (#PCDATA)>
        <!ELEMENT grade (#PCDATA)>

=== tangxin1998/Si4/SI4/Web/xml/src/note.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE information SYSTEM "note.dtd">



<information>
    <Student id1="01">
        <name>WANGtONG</name>
        <course>java</course>
        <grade>89</grade>
    </Student>
    <Student id1="02">
        <name>LiJia</name>
        <course>sql</course>
        <grade>58</grade>
    </Student>
</information>
